@startuml
!include https://raw.githubusercontent.com/Kyrales/1C-ER-plantuml/refs/heads/extended/main.puml

title ER-диаграмма
caption Ввод нормативов и факта расхода сырья при производстве кондитерского изделия
footer 2025

package НСИ <<folder>> {

    _Справочник(Номенклатура, "Номенклатура"){
        ВидНоменклатуры
        ТипНоменклатуры
        НормативныйПроцентСухогоВещества
        ТребуетсяПроверкаЛабораторией
        Описание
    }
    _Справочник(СерииНоменклатуры, "Серии номенклатуры"){
        ВидНоменклатуры
    }
    _Справочник(РесурсныеСпецификации, "Ресурсные спецификации"){
        ОсновноеИзделие
        Количество
        НормативныйПроцентСухогоВещества
        Описание
        -- МатериалыИРаботы --
        Номенклатура
        Количество
    }
    _Справочник(Склады, "Склады")
    _Справочник(ВидыНоменклатуры, "Виды номенклатуры"){
        ТипНоменклатуры
        ИспользоватьСерии
    }
    _Перечисление(ТипыНоменклатуры, "Типы номенклатуры"){
        Товар
        Услуга
        Работа
    }

}

package Производство <<folder>> {

    _Документ(ПроизводствоБезЗаказа, "Производство без заказа"){
        Склад
        ВыходноеИзделие
        Серия
        РесурснаяСпецификация
        КоличествоПлан
        КоличествоФакт
        ПроцентСухогоВеществаПлан
        ПроцентСухогоВеществаФакт
        Комментарий
        -- МатериалыИРаботы --
        Номенклатура
        Серия
        КоличествоПлан
        КоличествоФакт
        ПроцентСухогоВеществаПлан
        ПроцентСухогоВеществаФакт
    }

    _РегистрНакопления(РасходыСырьяНаПроизводствоКондитерскихИзделий, "Расходы сырья на производство кондитерских изделий"){
        <$d> Номенклатура
        <$r> КоличествоПлан
        <$r> КоличествоФакт
        <$r> КоличествоВСухомВеществеПлан
        <$r> КоличествоВСухомВеществеФакт
    }

}


package Закупки <<folder>> {

    _Документ(ПриобретениеТоваровУслуг, "Приобретение товаров и услуг"){
        Склад
        Комментарий
        -- Товары --
        Номенклатура
        Серия
        Количество
    }

    _Документ(ЛабораторноеИсследование, "Лабораторное исследование"){
        ДокументОснование
        Комментарий
        -- Товары --
        Номенклатура
        Серия
        ПроцентСухогоВещества
    }

    _РегистрНакопления(ТоварыНаСкладах, "Товары на складах"){
        <$d> Номенклатура
        <$d> Склад
        <$d> Серия
        <$r> Количество
    }

    _РегистрСведений(ЗначенияПроцентаСухихВеществ, "Значения процента сухих веществ"){
        <$d> Номенклатура
        <$d> Серия
        <$r> ПроцентСухогоВещества
    }
}

ТипыНоменклатуры --> ВидыНоменклатуры::ТипНоменклатуры

ВидыНоменклатуры --> Номенклатура::ВидНоменклатуры
ТипыНоменклатуры --> Номенклатура::ТипНоменклатуры

ВидыНоменклатуры --> СерииНоменклатуры::ВидНоменклатуры

Номенклатура --> РесурсныеСпецификации::ОсновноеИзделие
Номенклатура --> РесурсныеСпецификации::Номенклатура

Склады --> ПроизводствоБезЗаказа::Склад
Номенклатура --> ПроизводствоБезЗаказа::ВыходноеИзделие
РесурсныеСпецификации --> ПроизводствоБезЗаказа::РесурснаяСпецификация
Номенклатура --> ПроизводствоБезЗаказа::Номенклатура
СерииНоменклатуры --> ПроизводствоБезЗаказа::Серия

Склады --> ПриобретениеТоваровУслуг::Склад
Номенклатура --> ПриобретениеТоваровУслуг::Номенклатура
СерииНоменклатуры --> ПриобретениеТоваровУслуг::Серия

ПриобретениеТоваровУслуг --> ЛабораторноеИсследование::ДокументОснование
Номенклатура --> ЛабораторноеИсследование::Номенклатура
СерииНоменклатуры --> ЛабораторноеИсследование::Серия

ПриобретениеТоваровУслуг --> ТоварыНаСкладах : Регистратор
ПроизводствоБезЗаказа --> ТоварыНаСкладах : Регистратор
Склады --> ТоварыНаСкладах::Склад
Номенклатура --> ТоварыНаСкладах::Номенклатура
СерииНоменклатуры --> ТоварыНаСкладах::Серия

ЛабораторноеИсследование --> ЗначенияПроцентаСухихВеществ : Регистратор
ПроизводствоБезЗаказа --> ЗначенияПроцентаСухихВеществ : Регистратор
Номенклатура --> ЗначенияПроцентаСухихВеществ::Номенклатура
СерииНоменклатуры --> ЗначенияПроцентаСухихВеществ::Серия

ПроизводствоБезЗаказа --> РасходыСырьяНаПроизводствоКондитерскихИзделий : Регистратор
Номенклатура --> РасходыСырьяНаПроизводствоКондитерскихИзделий::Номенклатура

@enduml