@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

' LAYOUT_WITH_LEGEND()

title Ввод нормативов и факта расхода сырья при производстве кондитерского изделия

Person(МенеджерТехнологЦехаКондИзд, "Менеджер-технолог цеха кондитерских изделий", "")
Person(МенеджерТехнологЦехаПолуф, "Менеджер-технолог цеха полуфабрикатов", "")
Person(Кладовщик, "Кладовщик", "")
Person(ИнженерПоКачеству, "Инженер по качеству сырья и материалов", "")
Person(СтаршийМенеджерТехнологЦехаКондИзд, "Старший менеджер-технолог цеха кондитерских изделий", "")

' Системы

System_Boundary(ERP, "1С:ERP") {
    Container(ERPЗакупки, "Закупки", "Приобретение товаров и услуг")
    Container(ERPУчетНСИ, "Учет НСИ", "Номенклатура, ресурсные спецификации")
    Container(ERPПроизводство, "Производство", "Производство без заказа, отчет по контролю сырья")
}

System_Boundary(LIMS, "1С:LIMS") {
    Container(LIMSУправлениеКачеством, "Управление качеством")
}

System_Ext(Kafka, "Kafka")

' Связи

Rel(МенеджерТехнологЦехаКондИзд, ERPПроизводство, "Ввод данных")
Rel(МенеджерТехнологЦехаПолуф, ERPПроизводство, "Ввод данных")
Rel(СтаршийМенеджерТехнологЦехаКондИзд, ERPПроизводство, "Формирование отчетности")
Rel(Кладовщик, ERPЗакупки, "Ввод данных")
Rel(ИнженерПоКачеству, LIMSУправлениеКачеством, "Ввод данных")

Rel(ERPУчетНСИ, ERPПроизводство, "Номенклатура, ресурсные спецификации")
Rel(ERPЗакупки, ERPПроизводство, "Серии номенклатуры")

Rel(ERPЗакупки, Kafka, "Приобретение товаров и услуг", "kafka")
Rel(Kafka, LIMSУправлениеКачеством, "Приобретение товаров и услуг", "kafka")
Rel(Kafka, ERPЗакупки, "Лабораторное исследование", "kafka")
Rel(LIMSУправлениеКачеством, Kafka, "Лабораторное исследование", "kafka")

@enduml
